version: "3.8"

services:
  php:
    image: php:8.0-apache
    container_name: php_modulo3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_modulo3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/db/projetoFinal.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
    driver: local
